permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: 老张
  email: zx68555@163.com
  link: http://blog.aiphper.com

# 站点信息
title: 老张的个人博客
description: 关注开源，分享，学习，持续
url: http://blog.aiphper.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/img/avatar.png
favicon: /assets/img/ico.png
# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# disqus 设置
disqus:
  shortname: zx68555


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
# filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   zx68555
# codepen:  username
# dribbble: username
